# Generated by Django 5.2.4 on 2025-07-24 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_Entrega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verduras',
            name='fecha_cosecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='verduras',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
